version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - my_network
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: redis-container
    networks:
      - my_network
    ports:
      - "6379:6379"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch-container
    networks:
      - my_network
    ports:
      - "9200:9200"

  express:
    image: liuyychn/mat-express-microservice
    container_name: myexpress-container
    networks:
      - my_network
    ports:
      - "9000:8080" # Assuming your Express app runs on port 9000
    depends_on:
      - mysql
      - redis
      - elasticsearch

networks:
  my_network:
    driver: bridge
