version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - my_network
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: redis-container
    networks:
      - my_network
    ports:
      - "6379:6379"

  express:
    image: liuyychn/mat-express-microservice
    container_name: myexpress-container
    networks:
      - my_network
    ports:
      - "9000:8080" # Assuming your Express app runs on port 3000
    depends_on:
      - mysql
      - redis

networks:
  my_network:
    driver: bridge
