mysql:
    development:
        host: "localhost"
        user: "root"
        password: "my-secret-pw"
        database: "online_store"
        waitForConnections: true
        connectionLimit: 10
        connectTimeout: 100
        queueLimit: 0

    test:
        host: "localhost"
        user: "root"
        password: "my-secret-pw"
        database: "online_store"
        waitForConnections: true
        connectionLimit: 10
        connectTimeout: 100
        queueLimit: 0

    production:
        host: "mysql-container"
        user: "root"
        password: "my-secret-pw"
        database: "online_store"
        waitForConnections: true
        connectionLimit: 10
        connectTimeout: 100
        queueLimit: 0
