elasticsearch:
    development:
        node: "http://localhost:9200"
        username: ""
        password: ""

    test:
        node: "http://localhost:9200"
        username: ""
        password: ""

    production:
        node: "http://elasticsearch-container:9200"
        username: ""
        password: ""
